# Generated by Django 4.2.7 on 2023-12-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutohausREST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_auto', models.CharField(max_length=100)),
                ('model_auto', models.CharField(max_length=100)),
                ('engine_fuel', models.CharField(max_length=100)),
                ('engine_volume', models.DecimalField(decimal_places=1, max_digits=2)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('auto_img', models.ImageField(upload_to='img/')),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
